<title>Roomba | T&eacute;rminos y usos</title>
<table width="779" border="0" cellpadding="0" cellspacing="0">
  <!--DWLayoutTable-->
  <tr>
    <td width="779" height="7144" valign="top"><p>Condiciones de Uso<br>
      D&iacute;a de la &uacute;ltima revisi&oacute;n: 7 de Abril de 2008.<br>
      La traducci&oacute;n a Espa&ntilde;ol del presente documento se proporciona &uacute;nicamente a efectos informativos. En caso de conflicto, la versi&oacute;n del documento en ingl&eacute;s (publicada aqu&iacute; Aqui) ser&aacute; la &uacute;nica versi&oacute;n legalmente vinculante que regular&aacute; tu relaci&oacute;n con ROOMBA.</p>
      <p>Bienvenido a ROOMBA, una red social que te permitir&aacute; conectarte con las personas de tu entorno. El servicio y la red ROOMBA (conjuntamente,</p>
      <p>LEE ATENTAMENTE ESTAS CONDICIONES DE USO, DADO QUE CONTIENEN INFORMACI&Oacute;N IMPORTANTE ACERCA DE TUS DERECHOS LEGALES, LOS MEDIOS PARA HACER VALER TALES DERECHOS Y TUS OBLIGACIONES. ESTAS CONDICIONES INCLUYEN DIVERSAS LIMITACIONES Y EXCLUSIONES, AS&Iacute; COMO UNA CL&Aacute;USULA DE RESOLUCI&Oacute;N DE CONFLICTOS QUE REGULA EL MODO EN QUE SE DIRIMIR&Aacute; CUALQUIER CONTROVERSIA.<br>
        Admisi&oacute;n</p>
      <p>La admisi&oacute;n como miembro del Servicio no es posible en aquellos supuestos en que est&eacute; prohibida. Este Sitio est&aacute; destinado exclusivamente a usuarios mayores de trece (13) a&ntilde;os y a usuarios del Sitio menores de 18 a&ntilde;os que est&eacute;n cursando estudios de ense&ntilde;anza secundaria o superior. El registro en el Sitio, su uso o el acceso al mismo por parte de personas menores de 13 a&ntilde;os, o por personas menores de 18 a&ntilde;os que no est&eacute;n cursando estudios de ense&ntilde;anza secundaria o superior no est&aacute; permitido, no se autoriza bajo licencia y constituye una infracci&oacute;n de las presentes Condiciones de Uso. Al usar el Servicio o el Sitio, manifiestas y garantizas que eres mayor de 13 a&ntilde;os y est&aacute;s cursando estudios de ense&ntilde;anza secundaria o superior, o bien que eres mayor de 18 a&ntilde;os, y aceptas y te obligas a cumplir todos los t&eacute;rminos y condiciones del presente Contrato.<br>
        Datos de Registro; Seguridad de la Cuenta</p>
      <p>In consideration of your use of the Site, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the Site (&quot;Registration Data&quot;); (b) maintain the security of your password and identification; (c) maintain and promptly update the Registration Data, and any other information you provide to Company, to keep it accurate, current and complete; and (d) be fully responsible for all use of your account and for any actions that take place using your account.<br>
        Derechos Exclusivos sobre el Contenido del Sitio; Licencia Limitada</p>
      <p>Todo el contenido del Sitio y todo el contenido disponible a trav&eacute;s del Servicio, incluyendo dise&ntilde;os, texto, gr&aacute;ficos, im&aacute;genes, video, informaci&oacute;n, aplicaciones, software, m&uacute;sica, sonido y otros archivos, as&iacute; como su selecci&oacute;n y disposici&oacute;n (el<br>
        Marcas</p>
      <p>32665, ROOMBA, THE ROOMBA, ROOMBAHIGH, ROOMBANK, POKE, THE WALL y otros gr&aacute;ficos, logotipos, dise&ntilde;os, encabezamientos de p&aacute;ginas, iconos de botones, secuencias de comandos y nombres de servicio de la Compa&ntilde;&iacute;a son marcas registradas, marcas o im&aacute;genes de marca de la Compa&ntilde;&iacute;a en EE.UU. y/o otros pa&iacute;ses. Las marcas e im&aacute;genes de marca de la Compa&ntilde;&iacute;a no podr&aacute;n utilizarse, ni siquiera como parte de marcas y/o nombres de dominio, en relaci&oacute;n con ning&uacute;n producto o servicio de forma que puedan causar confusi&oacute;n y no podr&aacute;n copiarse, imitarse o utilizarse, total o parcialmente, sin el previo consentimiento por escrito de la Compa&ntilde;&iacute;a.<br>
        User Conduct</p>
      <p>Entiendes que, exceptuando los programas de publicidad que ofrecemos en el Sitio (p.ej., ROOMBA Flyers, ROOMBA Marketplace), el Servicio y el Sitio se ofrecen de forma exclusiva para tu uso personal y no comercial. Declaras, garantizas y aceptas que ninguno de los materiales enviados a trav&eacute;s de tu cuenta o que publiques, transmitas o compartas a trav&eacute;s del Servicio infringir&aacute; los derechos de cualquier tercero, incluyendo los derechos de autor, marca, privacidad, publicidad u otros derechos personales o de propiedad intelectual; y que no incluir&aacute;n ning&uacute;n contenido denigrante, difamatorio o ilegal.</p>
      <p>Adicionalmente, te obligas a no utilizar el Servicio o el Sitio para:</p>
      <p> * harvest or collect email addresses or other contact information of other users from the Service or the Site by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;<br>
        * usar el Servicio o el Sitio de forma ilegal o de forma que pueda da&ntilde;ar, deshabilitar, sobrecargar o perjudicar el Sitio;<br>
        * usar secuencias de comandos automatizadas para recopilar informaci&oacute;n a trav&eacute;s del Servicio o del Sitio o para interactuar de cualquier otro modo con los mismos;<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar cualquier contenido que se considere da&ntilde;ino, amenazante, ilegal, difamatorio, infractor, abusivo, incendiario, acosador, vulgar, obsceno, fraudulento, que vulnere el derecho a la intimidad y la propia imagen, que sea malicioso o cuestionable por motivos de raza, etnia o cualquier otro;<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar videos que no sean de naturaleza personal y que: (i) sean relativos a ti o a tus amigos, (ii) hayan sido grabados por ti o por tus amigos, o (iii) sean obras o animaciones originales creadas por ti o por tus amigos;<br>
        * registrar m&aacute;s de una cuenta de Usuario, registrar una cuenta de Usuario en nombre de otra persona o registrar una cuenta de Usuario en nombre de un grupo o entidad;<br>
        * hacerte pasar por otra persona o entidad, realizar manifestaciones falsas o proporcionar informaci&oacute;n falsa acerca de ti, tu edad o tu relaci&oacute;n con cualquier persona o entidad;<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar publicidad no solicitada o no autorizada, ofrecimientos il&iacute;citos, materiales promocionales,<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar en el Sitio datos personales de cualquier tercero, incluyendo direcciones, n&uacute;meros de tel&eacute;fono, direcciones de correo electr&oacute;nico, n&uacute;meros de la Seguridad Social o n&uacute;meros de tarjetas de cr&eacute;dito;<br>
        * solicitar datos personales a menores de 18 a&ntilde;os o solicitar contrase&ntilde;as o datos de car&aacute;cter personal con fines comerciales o il&iacute;citos;<br>
        * cargar, publicar, transmitir, compartir o facilitar material que contenga virus inform&aacute;ticos o cualquier otro c&oacute;digo, archivo o programa inform&aacute;tico dise&ntilde;ado para interrumpir, destruir o limitar la funcionalidad de cualquier software o hardware o equipo de telecomunicaciones;<br>
        * intimidar o acosar a otras personas;<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar contenido que constituya, incite o proporcione instrucciones para cometer delitos, que infrinja los derechos de un tercero, d&eacute; lugar responsabilidades o vulnere cualquier ley de &aacute;mbito local, estatal, nacional o internacional;<br>
        * usar o intentar usar la cuenta, el servicio o el sistema de otra persona sin la autorizaci&oacute;n de la Compa&ntilde;&iacute;a, o crear una identidad falsa para usar el Servicio o el Sitio.<br>
        * cargar, publicar, transmitir, compartir, almacenar o facilitar contenido que, a juicio exclusivo de la Compa&ntilde;&iacute;a, sea cuestionable o que restrinja o impida el uso o disfrute del Sitio por otras personas, o que pueda exponer a la Compa&ntilde;&iacute;a o a sus usuarios a da&ntilde;os o responsabilidades de cualquier tipo.</p>
      <p>Sin limitaci&oacute;n de lo anterior, tambi&eacute;n te obligas a cumplir nuestro C&oacute;digo de Conducta de ROOMBA, que proporciona informaci&oacute;n adicional acerca de la conducta autorizada de los usuarios de ROOMBA.<br>
        Contenido de Usuario Publicado en el Sitio</p>
      <p>Ser&aacute;s enteramente responsable de las fotos, perfiles (incluyendo tu nombre, imagen y representaci&oacute;n de tu persona), mensajes, notas, texto, informaci&oacute;n, m&uacute;sica, video, anuncios, listas y dem&aacute;s contenido que cargues, publiques o muestres (en adelante,</p>
      <p>Al publicar Contenido de Usuario en el Sitio, nos autorizas e instruyes para que realicemos las copias del mismo que estimemos necesarias para facilitar la publicaci&oacute;n y el almacenamiento del Contenido de Usuario en el Sitio. Al publicar el Contenido de Usuario en cualquier parte del Sitio, otorgas autom&aacute;ticamente a la Compa&ntilde;&iacute;a, y manifiestas y garantizas que tienes derecho a otorgar a la Compa&ntilde;&iacute;a, una licencia irrevocable, perpetua, no exclusiva, transferible, plenamente desembolsada y mundial (con derecho de sublicencia) para usar, copiar, reproducir p&uacute;blicamente, mostrar p&uacute;blicamente, reformatear, traducir, obtener extractos (totales o parciales) y distribuir dicho Contenido de Usuario para cualquier fin, ya sea comercial, publicitario o de otro tipo, en relaci&oacute;n con el Sitio o la promoci&oacute;n del mismo, para preparar trabajos derivados de dicho Contenido de Usuario o incorporarlo a otros trabajos, y para otorgar y autorizar sublicencias de lo anterior. Podr&aacute;s retirar tu Contenido de Usuario del Sitio en cualquier momento. Si decides retirar tu Contenido de Usuario, la licencia otorgada conforme a lo dispuesto anteriormente quedar&aacute; autom&aacute;ticamente revocada. No obstante lo anterior, reconoces que la Compa&ntilde;&iacute;a podr&aacute; conservar copias archivadas de tu Contenido de Usuario. ROOMBA no reivindica ning&uacute;n derecho de propiedad sobre tu Contenido de Usuario y reconoce frente a ti que, con sujeci&oacute;n a los derechos que nos asisten en virtud de las presentes Condiciones, conservar&aacute;s la titularidad exclusiva de todo tu Contenido de Usuario y cualesquiera derechos de propiedad intelectual o autor vinculados a tu Contenido de Usuario.<br>
        Servicios M&oacute;viles de ROOMBA</p>
      <p>The Service includes certain services that are available via your mobile phone, including (i) the ability to upload content to ROOMBA via your mobile phone (Mobile Uploads), (ii) the ability to receive and reply to ROOMBA messages, to poke and receive pokes and to write wall posts using text messaging (Mobile Texts), (iii) the ability to browse ROOMBA from your mobile phone (Mobile Web), and (iv) the ability to access certain ROOMBA features through a mobile application you have downloaded and installed on your mobile phone (Mobile Client) (collectively the &quot;Mobile Services&quot;). We do not charge for these Mobile Services. However, your carrier's normal messaging, data and other rates and fees will still apply. You should check with your carrier to find out what plans are available and how much they cost. In addition, downloading, installing, or using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services may work with all carriers or devices. Therefore, you should check with your carrier to find out if the Mobile Services are available for your mobile devices, and what restrictions, if any, may be applicable to your use of such Mobile Services. By using the Mobile Services, you agree that we may communicate with you regarding ROOMBA and other entities by SMS, MMS, text message or other electronic means to your mobile device and that certain information about your usage of the Mobile Services may be communicated to us. In the event you change or deactivate your mobile telephone number, you agree to promptly update your ROOMBA account information to ensure that your messages are not sent to the person that acquires your old number.<br>
        Reclamaciones por Infracci&oacute;n de Derechos de Autor</p>
      <p>Respetamos los derechos de propiedad intelectual de terceros y prohibimos que los usuarios carguen, publiquen o transmitan en el sitio web o en el servicio de ROOMBA cualquier material que infrinja los derechos de propiedad intelectual de un tercero. Cuando recibamos formalmente una Advertencia de Presunta Infracci&oacute;n de Derechos de Autor, seg&uacute;n se describe en nuestra Pol&iacute;tica de ROOMBA en materia de Protecci&oacute;n de Derechos de Autor, retiraremos o deshabilitaremos inmediatamente el acceso al material presuntamente infractor y cerraremos las cuentas de cualquier infractor reincidente de conformidad con lo dispuesto en el presente documento y en la Ley de Protecci&oacute;n de Derechos de Autor en la Era Digital (Digital Millenium Copyright Act). Si consideras que alg&uacute;n material del Sitio infringe cualquier derecho de autor del que seas titular o que se encuentre bajo tu control, podr&aacute;s notificar por escrito dicha infracci&oacute;n a nuestro Agente Designado. Consulta la Pol&iacute;tica de ROOMBA en materia de Protecci&oacute;n de Derechos de Autor para obtener m&aacute;s informaci&oacute;n sobre c&oacute;mo denunciar infracciones de derechos de autor.<br>
        Pol&iacute;tica sobre Infractores Reincidentes</p>
      <p>De conformidad con la Digital Millennium Copyright Act (DMCA) y dem&aacute;s leyes aplicables, la Compa&ntilde;&iacute;a ha adoptado, como pol&iacute;tica, la expulsi&oacute;n de aquellos miembros que considere infractores reincidentes en determinadas circunstancias y a su elecci&oacute;n exclusiva. La Compa&ntilde;&iacute;a podr&aacute; asimismo y a su libre elecci&oacute;n limitar el acceso al Sitio y/o expulsar a aquellos usuarios que infrinjan los derechos de propiedad intelectual de terceros, con independencia de que hayan reincidido o no en la comisi&oacute;n de la infracci&oacute;n.<br>
        Sitios Web y Contenido de Terceros</p>
      <p>El Sitio contiene (o es posible que recibas a trav&eacute;s del Sitio o del Servicio) v&iacute;nculos a otros sitios web (los<br>
        Servicio Compartir</p>
      <p>La Compa&ntilde;&iacute;a ofrece una funci&oacute;n que permite a los usuarios del Sitio compartir con otras personas o publicar sus propios perfiles de miembro, videos, art&iacute;culos y dem&aacute;s Aplicaciones, Software o Contenido de Terceros desde los Sitios de Terceros y/o v&iacute;nculos a los Sitios de Terceros, a trav&eacute;s del Servicio (el<br>
        Uso de V&iacute;nculos Compartir por los Proveedores de Contenido Online</p>
      <p>Con sujeci&oacute;n a los t&eacute;rminos y condiciones de las presentes Condiciones de Uso, los Sitios de Terceros que cumplan los requisitos expuestos a continuaci&oacute;n podr&aacute;n colocar un V&iacute;nculo Compartir (seg&uacute;n se describe a continuaci&oacute;n), de la forma que apruebe la Compa&ntilde;&iacute;a, en las p&aacute;ginas de sus sitios web para facilitar el uso del Servicio Compartir. Un Sitio de Terceros que coloque un V&iacute;nculo Compartir en su sitio se denominar&aacute; en el presente Contrato un</p>
      <p>En caso de que el V&iacute;nculo Compartir sea un bot&oacute;n que contenga iconos, im&aacute;genes gr&aacute;ficas, marcas u otros materiales propiedad de la Compa&ntilde;&iacute;a, se autoriza al Proveedor de Contenido Online para utilizar tales im&aacute;genes, marcas o materiales exclusivamente con la finalidad de colocar el V&iacute;nculo Compartir en el sitio del Proveedor de Contenido Online y &uacute;nicamente en el formato actual proporcionado por la Compa&ntilde;&iacute;a. En caso de que el V&iacute;nculo Compartir sea un v&iacute;nculo de texto, deber&aacute; incluir la palabra</p>
      <p>Para que un Proveedor de Contenido Online incluya un V&iacute;nculo Compartir en sus p&aacute;ginas, el Sitio de Terceros no deber&aacute; incluir ning&uacute;n contenido web cuyo uso compartido o publicaci&oacute;n por parte de un usuario constituya una infracci&oacute;n de las normas de conducta para usuarios establecidas anteriormente. Sin limitaci&oacute;n de lo anterior, el Proveedor de Contenido Online se obliga a no publicar V&iacute;nculos Compartir en ning&uacute;n sitio web que incluya, y manifiesta y garantiza que dicho sitio web no incluye ni incluir&aacute;, contenido infractor, da&ntilde;ino, amenazante, ilegal, difamatorio, abusivo, incendiario, acosador, vulgar, obsceno, lascivo, fraudulento, que vulnere el derecho a la intimidad y la propia imagen o pueda exponer a la Compa&ntilde;&iacute;a o a sus usuarios a cualquier tipo de da&ntilde;os o responsabilidades. Al incluir un V&iacute;nculo Compartir, el Proveedor de Contenido Online se obliga a defender, exonerar de toda responsabilidad y mantener indemnes a la Compa&ntilde;&iacute;a, sus filiales y entidades vinculadas, y a cada uno de sus administradores, directivos, agentes, contratistas, socios y empleados, frente a las p&eacute;rdidas, responsabilidades, reclamaciones, demandas, da&ntilde;os, costes y gastos, incluyendo honorarios razonables de abogados, que puedan derivarse de la inclusi&oacute;n del V&iacute;nculo Compartir, cualesquiera v&iacute;nculos, contenidos, elementos o materiales que puedan ser compartidos o publicados a trav&eacute;s del V&iacute;nculo Compartir, o del incumplimiento o presunto incumplimiento de las manifestaciones y garant&iacute;as establecidas anteriormente.</p>
      <p>Al incluir un V&iacute;nculo Compartir, el Proveedor de Contenido Online otorga autom&aacute;ticamente, y manifiesta y garantiza que tiene derecho a otorgar a la Compa&ntilde;&iacute;a, una licencia irrevocable, perpetua, no exclusiva, transferible, plenamente desembolsada y mundial (con derecho de sublicencia) para usar el Servicio Compartir con el fin de colocar v&iacute;nculos, usar, copiar, publicar, transmitir, reproducir p&uacute;blicamente, mostrar p&uacute;blicamente, reformatear, traducir, obtener extractos (totales o parciales), resumir y distribuir el contenido, los v&iacute;nculos y dem&aacute;s materiales de cualquier tipo que est&eacute;n publicados en cualesquiera p&aacute;ginas web en las que el Proveedor de Contenido Online coloque el V&iacute;nculo Compartir.<br>
        ROOMBA Marketplace</p>
      <p>Todas las listas publicadas en el servicio ROOMBA Marketplace y todas las operaciones realizadas en relaci&oacute;n con dicho servicio se regir&aacute;n por las Directrices sobre ROOMBA Marketplace (las<br>
        Aplicaciones de la Plataforma ROOMBA</p>
      <p>La Plataforma ROOMBA es un conjunto de APIs y servicios que ROOMBA proporciona para permitir que terceros desarrolladores (los</p>
      <p>Los Desarrolladores de Plataformas podr&aacute;n utilizar la Plataforma ROOMBA y crear Aplicaciones de la Plataforma &uacute;nicamente de conformidad con los t&eacute;rminos y condiciones establecidos en un contrato suscrito entre ROOMBA y el Desarrollador de Plataformas (las</p>
      <p>Los Usuarios que instalen Aplicaciones de la Plataforma deber&aacute;n aceptar los t&eacute;rminos y condiciones establecidos en las Condiciones de Uso de las Aplicaciones de la Plataforma (las</p>
      <p>Si t&uacute;, tus amigos o los miembros de tu red utilizan cualesquiera Aplicaciones de la Plataforma, es posible que tales Aplicaciones de la Plataforma accedan a determinada informaci&oacute;n relativa a ti y la compartan con terceros de conformidad con tu configuraci&oacute;n de privacidad, conforme se describe m&aacute;s detalladamente en nuestra Pol&iacute;tica de Privacidad. Los Desarrolladores de Plataformas est&aacute;n obligados a aceptar restricciones sobre el acceso, el almacenamiento y la utilizaci&oacute;n de dicha informaci&oacute;n. No obstante lo anterior y aunque hemos adoptado medidas contractuales y t&eacute;cnicas para limitar la posible utilizaci&oacute;n no autorizada de dicha informaci&oacute;n por parte de los Desarrolladores de Plataformas, no seleccionamos ni aprobamos a los Desarrolladores, y no podemos garantizar que todos los Desarrolladores de Plataformas cumplir&aacute;n tales restricciones y los acuerdos correspondientes. Determinadas acciones que realices a trav&eacute;s de las Aplicaciones de la Plataforma pueden mostrase a tus amigos en tu perfil, mini-feeds y feeds de noticias, y podr&aacute;s optar por no mostrar tales acciones en la p&aacute;gina de Configuraci&oacute;n de Privacidad. Te rogamos que comuniques cualquier posible uso indebido de la informaci&oacute;n a trav&eacute;s de la Plataforma ROOMBA seg&uacute;n se describe en nuestra Pol&iacute;tica de Privacidad.</p>
      <p>Podr&aacute;s configurar tus preferencias para tus feeds de noticias y mini-feeds aqu&iacute;.<br>
        P&aacute;ginas de ROOMBA</p>
      <p>Las P&aacute;ginas de ROOMBA son perfiles especiales que se utilizan exclusivamente con fines comerciales, pol&iacute;ticos o ben&eacute;ficos. No podr&aacute;s configurar una P&aacute;gina de ROOMBA en nombre de otra persona o entidad salvo que tengas autorizaci&oacute;n para hacerlo. Esto incluye las P&aacute;ginas de ROOMBA para fans, as&iacute; como las P&aacute;ginas de ROOMBA para apoyar o criticar a otras personas o entidades.</p>
      <p>ROOMBA NO FILTRA NI APRUEBA LAS P&Aacute;GINAS DE ROOMBA Y NO PUEDE GARANTIZAR QUE UNA P&Aacute;GINA DE ROOMBA HAYA SIDO REALMENTE CREADA Y EST&Eacute; SIENDO GESTIONADA POR LA PERSONA O ENTIDAD QUE CONSTITUYE EL OBJETO DE UNA P&Aacute;GINA DE ROOMBA. ASIMISMO, ROOMBA NO ES RESPONSABLE DEL CONTENIDO DE NINGUNA P&Aacute;GINA DE ROOMBA, NI DE LAS OPERACIONES REALIZADAS U OTRAS ACCIONES LLEVADAS A CABO EN RELACI&Oacute;N CON CUALQUIER P&Aacute;GINA DE ROOMBA, INCLUYENDO EL MODO EN QUE EL PROPIETARIO DE LA P&Aacute;GINA DE ROOMBA OBTIENE, TRATA, UTILIZA Y/O COMPARTE LOS DATOS PERSONALES QUE PUEDA OBTENER DE LOS USUARIOS (CONSULTA LA POL&Iacute;TICA DE PRIVACIDAD DE ROOMBA SI TIENES DUDAS ACERCA DE C&Oacute;MO SE UTILIZAN O COMPARTEN TUS DATOS PERSONALES). PRESTA ATENCI&Oacute;N ANTES DE FACILITAR DATOS PERSONALES O REALIZAR OPERACIONES EN RELACI&Oacute;N CON UNA P&Aacute;GINA DE ROOMBA.</p>
      <p>Con car&aacute;cter adicional a las presentes Condiciones de Uso, las P&aacute;ginas de ROOMBA est&aacute;n sujetas a determinadas Condiciones Adicionales Aplicables a las P&aacute;ginas de ROOMBA. Las Condiciones Adicionales Aplicables a las P&aacute;ginas de ROOMBA prevalecer&aacute;n en caso de conflicto entre &eacute;stas y las Condiciones de Uso.<br>
        Condiciones de Venta</p>
      <p>Consulta nuestras Condiciones de Venta para conocer los t&eacute;rminos, condiciones y pol&iacute;ticas aplicables a tu operaci&oacute;n de compra de productos o servicios de la Compa&ntilde;&iacute;a. Al solicitar productos o servicios de la Compa&ntilde;&iacute;a a trav&eacute;s del Sitio, aceptas cumplir las Condiciones de Venta. Las Condiciones de Venta podr&aacute;n ser modificadas en cualquier momento y sin previo aviso, a elecci&oacute;n exclusiva de la Compa&ntilde;&iacute;a, por lo que deber&aacute;s revisar las Condiciones de Venta cada vez que realices una compra.<br>
        Conflictos de Usuario</p>
      <p>Como usuario, ser&aacute;s el &uacute;nico responsable de tus interacciones con otros usuarios de ROOMBA. Nos reservamos el derecho a controlar los conflictos que tengas con otros usuarios, si bien no vendremos obligados a ello.<br>
        Privacidad</p>
      <p>Nos preocupa la privacidad de nuestros usuarios. Haz clic aqu&iacute; para consultar la Pol&iacute;tica de Privacidad de ROOMBA. Al utilizar el Sitio o el Servicio, aceptas la transferencia de tus datos a Estados Unidos, as&iacute; como su tratamiento en dicho pa&iacute;s.<br>
        Exclusi&oacute;n de Responsabilidad</p>
      <p>La Compa&ntilde;&iacute;a no es responsable en modo alguno de ning&uacute;n Contenido de Usuario o de Aplicaciones, Software o Contenido de Terceros publicados en el Sitio o en relaci&oacute;n con el Servicio, con independencia de que hayan sido publicados u originados por usuarios del Sitio, ROOMBA, otros terceros o cualquiera de los equipos o programas asociados al Sitio o Servicio o utilizados en &eacute;stos. Aunque establecemos normas relativas a la conducta de los usuarios y a las publicaciones, no controlamos lo que los usuarios publican, transmiten o comparten en el Sitio, y no somos por tanto responsable de ello ni de ning&uacute;n contenido ofensivo, inapropiado, obsceno, ilegal o cuestionable que puedas encontrar en el Sitio o en relaci&oacute;n con cualquier Contenido de Usuario o Aplicaciones, Software o Contenido de Terceros. La Compa&ntilde;&iacute;a no es responsable de la conducta, online u offline, de ning&uacute;n usuario del Sitio o del Servicio.</p>
      <p>Ocasionalmente, el Sitio y el Servicio podr&aacute;n no estar disponibles temporalmente por motivos de mantenimiento o por otras causas. La Compa&ntilde;&iacute;a no asume ning&uacute;n tipo de responsabilidad por errores, omisiones, interrupciones, eliminaciones, defectos, retrasos de funcionamiento o de transmisi&oacute;n, fallos de la l&iacute;nea de comunicaciones, robos, destrucci&oacute;n, acceso no autorizado o alteraci&oacute;n de las comunicaciones del Usuario. La Compa&ntilde;&iacute;a no se hace responsable de ninguna aver&iacute;a t&eacute;cnica ni de ning&uacute;n otro problema de la red o el servicio telef&oacute;nico, de los sistemas inform&aacute;ticos, servidores o proveedores, equipos inform&aacute;ticos o de telefon&iacute;a m&oacute;vil, software, fallos del correo electr&oacute;nico o los servidores ocasionados por problemas t&eacute;cnicos o congesti&oacute;n de tr&aacute;fico en Internet o en cualquier Sitio (o en una combinaci&oacute;n de &eacute;stos), incluyendo lesiones o da&ntilde;os sobre el ordenador, el tel&eacute;fono m&oacute;vil o cualquier otro elemento de hardware o software del Usuario o de otra persona, derivados de la utilizaci&oacute;n o de la descarga de materiales en relaci&oacute;n con la Web y/o con el Servicio, incluyendo el software del Cliente M&oacute;vil. La Compa&ntilde;&iacute;a no ser&aacute; en ning&uacute;n caso responsable de p&eacute;rdidas o da&ntilde;os, incluyendo cualesquiera p&eacute;rdidas o da&ntilde;os sobre el Contenido de Usuario o lesiones personales o muertes, derivados de la utilizaci&oacute;n por parte de cualquier persona del Sitio, el Servicio, cualquier Contenido de Usuario o las Aplicaciones, Software o Contenido de Terceros publicados en el Sitio o el Servicio o transmitidos a Usuarios, o de las interacciones entre los usuarios del Sitio, ya sean online u offline.</p>
      <p>EL SITIO, EL SERVICIO (INCLUYENDO LOS SERVICIOS M&Oacute;VILES, EL SERVICIO COMPARTIR Y EL SERVICIO MARKETPLACE), LAS APLICACIONES DE LA PLATAFORMA Y EL CONTENIDO DEL SITIO SE PROPORCIONAN</p>
      <p>La Compa&ntilde;&iacute;a se reserva el derecho a modificar cualquier contenido, software y dem&aacute;s elementos utilizados o incluidos en el Sitio y en cualesquiera Servicios y Aplicaciones de la Plataforma ofrecidos a trav&eacute;s del Sitio en cualquier momento y sin previo aviso. Las referencias a productos, servicios, procesos u otras informaciones mediante nombres comerciales, marcas, fabricantes, proveedores u otros, no constituyen ni implican que la Compa&ntilde;&iacute;a apruebe, patrocine o recomiende tales productos, servicios, procesos o informaciones, ni que tenga ninguna relaci&oacute;n con &eacute;stos.<br>
        Limitaci&oacute;n de Responsabilidad</p>
      <p>EN NING&Uacute;N CASO SER&Aacute; LA COMPA&Ntilde;&Iacute;A O SUS DIRECTIVOS, EMPLEADOS O AGENTES RESPONSABLE FRENTE A TI U OTROS TERCEROS POR CUALESQUIERA DA&Ntilde;OS INDIRECTOS, EMERGENTES, EJEMPLARIZANTES, DERIVADOS, ESPECIALES O PUNITIVOS, INCLUYENDO P&Eacute;RDIDAS DE BENEFICIOS O DATOS DERIVADOS DE TU UTILIZACI&Oacute;N DEL SITIO O EL SERVICIO, LAS APLICACIONES DE LA PLATAFORMA, EL CONTENIDO DEL SITIO U OTROS MATERIALES A LO QUE SE HAYA ACCEDIDO A TRAV&Eacute;S DEL SITIO O DESCARGADOS DE &Eacute;STE, AUN CUANDO LA COMPA&Ntilde;&Iacute;A SEA CONSCIENTE O HAYA SIDO ADVERTIDA DE LA POSIBILIDAD DE DICHOS DA&Ntilde;OS. SIN PERJUICIO DE CUALQUIER DISPOSICI&Oacute;N PREVISTA EN CONTRARIO EN EL PRESENTE CONTRATO, LA RESPONSABILIDAD DE LA COMPA&Ntilde;&Iacute;A FRENTE A TI POR CUALQUIER CAUSA, Y CON INDEPENDENCIA DE LA FORMA DE ACTUACI&Oacute;N, QUEDAR&Aacute; LIMITADA EN TODO MOMENTO A LA CANTIDAD QUE HAYAS ABONADO, EN SU CASO, A LA COMPA&Ntilde;&Iacute;A POR EL SERVICIO DURANTE EL PERIODO DE TIEMPO QUE HAYAS SIDO MIEMBRO, SIN QUE EN NING&Uacute;N CASO LA RESPONSABILIDAD DE LA COMPA&Ntilde;&Iacute;A FRENTE A TI SUPERE $1.000. RECONOCES QUE EN CASO DE NO ABONAR NINGUNA CANTIDAD A LA COMPA&Ntilde;&Iacute;A POR EL SERVICIO, &Uacute;NICAMENTE TENDR&Aacute;S DERECHO A LA ADOPCI&Oacute;N DE MEDIDAS CAUTELARES, SALVO QUE LA LEY PERMITA LO CONTRARIO, Y NO TENDR&Aacute;S DERECHO A NING&Uacute;N TIPO DE INDEMNIZACI&Oacute;N DE LA COMPA&Ntilde;&Iacute;A EN CONCEPTO DE DA&Ntilde;OS Y PERJUICIOS, CON INDEPENDENCIA DE LA CAUSA DE ACCI&Oacute;N.<br>
        Cancelaci&oacute;n</p>
      <p>La Compa&ntilde;&iacute;a podr&aacute; cancelar tu condici&oacute;n de miembro, eliminar tu perfil y cualquier contenido o informaci&oacute;n que hayas publicado en el Sitio o a trav&eacute;s de cualquier Aplicaci&oacute;n de la Plataforma y/o prohibirte que utilices el Servicio, el Sitio o cualquier Aplicaci&oacute;n de la Plataforma, o que o accedas a &eacute;stos (o a cualquier parte, aspecto o funci&oacute;n del Servicio o el Sitio o cualquier Aplicaci&oacute;n de la Plataforma) por cualquier causa, o sin causa, en cualquier momento y a nuestra elecci&oacute;n exclusiva, con o sin preaviso, incluyendo cuando consideremos que eres menor de 13 a&ntilde;os, o menor de 18 y no est&aacute;s cursando estudios de ense&ntilde;anza secundaria o superior. Por norma general, si bien no vendremos obligados a ello, cuando se nos notifique que un usuario ha fallecido, mantendremos activa la cuenta de ese usuario de forma especial y conmemorativa durante un periodo de tiempo determinado para permitir a otros usuarios que publiquen y vean comentarios.<br>
        Ley Aplicable y Jurisdicci&oacute;n</p>
      <p>By visiting or using the Site and/or the Service, you agree that the laws of the State of Delaware, without regard to principles of conflict of laws, will govern these Terms of Use and any dispute of any sort that might arise between you and the Company or any of our affiliates. With respect to any disputes or claims not subject to arbitration (as set forth below), you agree not to commence or prosecute any action in connection therewith other than in the state and federal courts of California, and you hereby consent to, and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to, venue and jurisdiction in the state and federal courts of California.<br>
        Arbitration</p>
      <p>YOU AND COMPANY AGREE THAT, EXCEPT AS MAY OTHERWISE BE PROVIDED IN REGARD TO SPECIFIC SERVICES ON THE SITE IN ANY SPECIFIC TERMS APPLICABLE TO THOSE SERVICES, THE SOLE AND EXCLUSIVE FORUM AND REMEDY FOR ANY AND ALL DISPUTES AND CLAIMS RELATING IN ANY WAY TO OR ARISING OUT OF THESE TERMS OF USE, THE SITE AND/OR THE SERVICE (INCLUDING YOUR VISIT TO OR USE OF THE SITE AND/OR THE SERVICE) SHALL BE FINAL AND BINDING ARBITRATION, except that: (a) to the extent that either of us has in any manner infringed upon or violated or threatened to infringe upon or violate the other party's patent, copyright, trademark or trade secret rights, or you have otherwise violated any of the user conduct rules set forth above or in the Code of Conduct then the parties acknowledge that arbitration is not an adequate remedy at law and that injunctive or other appropriate relief may be sought; and (b) no disputes or claims relating to any transactions you enter into with a third party through the ROOMBA Marketplace may be arbitrated.</p>
      <p>El procedimiento arbitral contemplado en el presente Contrato se realizar&aacute; a trav&eacute;s de la Asociaci&oacute;n Americana de Arbitraje (American Arbitration Association -</p>
      <p>En la medida m&aacute;xima de lo permitido por la legislaci&oacute;n aplicable, NING&Uacute;N PROCEDIMIENTO ARBITRAL O RECLAMACI&Oacute;N QUE SE REFIERA A LOS PRESENTES T&Eacute;RMINOS Y CONDICIONES DE USO PODR&Aacute; CONSOLIDARSE CON OTROS PROCEDIMIENTOS ARBITRALES O RECLAMACIONES, INCLUYENDO LOS RELATIVOS A ACTUALES O ANTIGUOS USUARIOS DEL SERVICIO, Y NO SE PERMITIR&Aacute;N PROCEDIMIENTOS DE ARBITRAJE COLECTIVO. En ning&uacute;n caso podr&aacute;s iniciar ninguna reclamaci&oacute;n, acci&oacute;n legal o procedimiento judicial que est&eacute; relacionado de cualquier modo con el Sitio y/o el Servicio (incluyendo tu visita al Sitio y/o el Servicio, o tu utilizaci&oacute;n de &eacute;stos) cuando hayan transcurrido m&aacute;s de tres (3) a&ntilde;os desde la fecha en que se haya originado la causa de acci&oacute;n.<br>
        Exoneraci&oacute;n de Responsabilidad</p>
      <p>Aceptas exonerar de toda responsabilidad a la Compa&ntilde;&iacute;a, sus empresas asociadas y filiales y a sus respectivos administradores, directivos, agentes, contratistas, socios y empleados, frente a cualesquiera p&eacute;rdidas, responsabilidades, reclamaciones, demandas, da&ntilde;os, costes y gastos, incluyendo los honorarios razonables de abogados, derivados de cualquier Contenido de Usuario y cualquier tipo de Aplicaciones, Software o Contenido de Terceros que publiques o compartas a trav&eacute;s del Sitio (incluyendo a trav&eacute;s del Servicio Compartir), tu utilizaci&oacute;n del Servicio o el Sitio, tu conducta en relaci&oacute;n con el Servicio, el Sitio u otros usuarios del Servicio o el Sitio, o cualquier incumplimiento del presente Contrato, de cualesquiera leyes o derechos de un tercero.<br>
        Informaci&oacute;n Remitida</p>
      <p>Reconoces y aceptas que toda pregunta, comentario, sugerencia, idea, feedback u otra informaci&oacute;n relativa al Sitio o el Servicio (la<br>
        Definiciones e Interpretaci&oacute;n</p>
      <p>Salvo que se especifique lo contrario, se considerar&aacute; que los t&eacute;rminos<br>
        Disposiciones Generales</p>
      <p>Las presentes Condiciones de Uso constituyen el acuerdo completo entre t&uacute; y la Compa&ntilde;&iacute;a en relaci&oacute;n con el uso del Sitio y/o el Servicio, y sustituyen a todos los anteriores acuerdos entre t&uacute; y la Compa&ntilde;&iacute;a en relaci&oacute;n con tu utilizaci&oacute;n del Sitio o el Servicio. La omisi&oacute;n por parte de Compa&ntilde;&iacute;a en el ejercicio o la exigencia de cumplimiento de cualquier derecho o disposici&oacute;n de las presentes Condiciones de Uso no constituir&aacute; una renuncia a dicho derecho o disposici&oacute;n en ese caso concreto o en cualquier otro. Si alguna disposici&oacute;n del presente Contrato es declarada inv&aacute;lida, el resto del presente Contrato permanecer&aacute; vigente en todos sus aspectos. Si cualquier disposici&oacute;n de las presentes Condiciones de Uso es declarada ilegal, nula o inaplicable por cualquier causa, esa disposici&oacute;n quedar&aacute; excluida de las presentes Condiciones de Uso sin afectar a la validez y aplicabilidad de las restantes disposiciones.<br>
        Preguntas</p>
      <p>Please visit our Ayuda page or these links for more information.</p>      <p> * Pol&iacute;tica de ROOMBA en materia de Protecci&oacute;n de Derechos de Autor<br>
        * Condiciones de Venta de ROOMBA<br>
        * Directrices sobre ROOMBA Marketplace<br>
        * Directrices sobre las Aplicaciones de la Plataforma ROOMBA<br>
        * Condiciones de Uso de las Aplicaciones de la Plataforma<br>
    * Condiciones del Servicio para Desarrolladores de ROOMBA</p></td>
  </tr>
</table>
